---
- name: Fetch Fedora release metadata
  ansible.builtin.uri:
    url: https://getfedora.org/releases.json
  register: fedora_releases

- name: Get latest version of Fedora
  ansible.builtin.set_fact:
    fedora_version: "{{ fedora_releases.json | map(attribute='version') | max }}"
  when: fedora_iso_version == "latest"

- name: Extract ISO link
  ansible.builtin.set_fact:
    fedora_iso_info: |
      {{
        fedora_releases.json |
        selectattr("version", "eq", fedora_iso_version) |
        selectattr("arch", "eq", fedora_iso_arch_map[fedora_iso_architecture]) |
        selectattr("variant", "eq", fedora_iso_variant) |
        selectattr("link", "search", ".iso") |
        first
      }}

- name: Set fact for ISO link
  ansible.builtin.set_fact:
    fedora_iso_link: "{{ fedora_iso_info.link }}"
