---
- name: Populate authorized_keys from GitHub
  hosts: all
  become: true
  vars:
    remote_user: "{{ ansible_user | default('root') }}"
    github_users:
      - shanemcd
    clear_existing: false  # Set to true to wipe existing authorized_keys before populating

  tasks:
    - name: Ensure ~/.ssh directory exists
      file:
        path: "/home/{{ remote_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"

    - name: Clear existing authorized_keys if requested
      copy:
        content: ""
        dest: "/home/{{ remote_user }}/.ssh/authorized_keys"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: '0600'
      when: clear_existing | bool

    - name: Add GitHub user keys
      ansible.posix.authorized_key:
        user: "{{ remote_user }}"
        state: present
        key: "https://github.com/{{ item }}.keys"
      loop: "{{ github_users }}"
